version: '3.8'
services:
  devops:
    image: hanvitha/devops
    ports:
      - "81:80"
    deploy:
      replicas: 3
  aws:
    image: hanvitha/aws
    ports:
      - "82:80"
    deploy:
      replicas: 3
  linux:
    image: hanvitha/linux
    ports:
      - "83:80"
    deploy: 
      replicas: 3
  python:
    image: hanvitha/python
    ports:
      - "84:80"
    deploy:
      replicas: 3
